import type { Project } from '../types'

export const projects: Project[] = [
  {
    id: 13,
    name: 'Roma Massas',
    slug: 'roma-massas',
    demo: 'https://romamassas.com.br/',
    github: null,
    origin: 'client',
    type: 'Institucional',
    segment: 'Alimentos',
    desc: 'Site institucional com catálogo de produtos, narrativa de tradição artesanal e captação de pedidos pelo WhatsApp.',
    tags: ['WordPress', 'PHP', 'JavaScript'],
    color: '#e5ce43',
  },
  {
    id: 1,
    name: 'Ferreira & Associados',
    slug: 'lp-advogado',
    demo: 'https://advocacia-prime-br.vercel.app',
    type: 'Landing Page',
    segment: 'Advocacia',
    desc: 'Escritório premium com direção visual elegante, partículas douradas e experiência responsiva.',
    tags: ['React', 'Framer Motion', 'Tailwind'],
    color: '#ff4df0',
  },
  {
    id: 2,
    name: 'NexusAI',
    slug: 'site-tech-startup',
    demo: 'https://tech-startup-br.vercel.app',
    type: 'Institucional',
    segment: 'Tech / IA',
    desc: 'Startup de IA futurista com canvas animado, glassmorphism e narrativa de produto.',
    tags: ['React', 'Canvas API', 'Framer Motion'],
    color: '#8f7cff',
  },
  {
    id: 3,
    name: 'Sorriso Perfeito',
    slug: 'lp-dentista',
    demo: 'https://clinica-sorriso-br.vercel.app',
    type: 'Landing Page',
    segment: 'Odontologia',
    desc: 'Clínica moderna com fluxo de agendamento, visual leve e foco em conversão.',
    tags: ['React', 'Framer Motion', 'Tailwind'],
    color: '#8f7cff',
  },
  {
    id: 4,
    name: 'Dark Ink Studio',
    slug: 'lp-tatuador',
    demo: 'https://ink-studio-br.vercel.app',
    type: 'Landing Page',
    segment: 'Tatuagem',
    desc: 'Experiência underground com textura, glitch, vídeo e tipografia de alto impacto.',
    tags: ['React', 'Framer Motion', 'Tailwind'],
    color: '#8f7cff',
  },
  {
    id: 5,
    name: 'Alma Gastronomia',
    slug: 'lp-restaurante',
    demo: 'https://sabor-bistro-br.vercel.app',
    type: 'Landing Page',
    segment: 'Restaurante',
    desc: 'Site gastronômico editorial com cardápio interativo, atmosfera e movimento sutil.',
    tags: ['React', 'Framer Motion', 'Tailwind'],
    color: '#8f7cff',
  },
  {
    id: 6,
    name: 'APEX Training',
    slug: 'lp-academia',
    demo: 'https://academia-power-br.vercel.app',
    type: 'Landing Page',
    segment: 'Academia',
    desc: 'Landing page energética com vídeo, contadores e hierarquia visual voltada a matrículas.',
    tags: ['React', 'Framer Motion', 'Tailwind'],
    color: '#8f7cff',
  },
  {
    id: 7,
    name: 'Prestige Imóveis',
    slug: 'site-imobiliaria',
    demo: 'https://imovel-prime-br.vercel.app',
    type: 'Institucional',
    segment: 'Imobiliária',
    desc: 'Imobiliária de alto padrão com busca, filtros e apresentação cinematográfica.',
    tags: ['React', 'Framer Motion', 'Tailwind'],
    color: '#8f7cff',
  },
  {
    id: 8,
    name: 'FluxCRM',
    slug: 'lp-saas',
    demo: 'https://saas-flow-br.vercel.app',
    type: 'SaaS',
    segment: 'Software B2B',
    desc: 'Produto SaaS com pipeline visual, interface limpa e comunicação orientada a valor.',
    tags: ['React', 'Framer Motion', 'Tailwind'],
    color: '#8f7cff',
  },
  {
    id: 9,
    name: 'LUMIÈRE',
    slug: 'lp-ecommerce-moda',
    demo: 'https://moda-vitrine-br.vercel.app',
    type: 'E-commerce',
    segment: 'Moda',
    desc: 'Boutique luxury com direção editorial, catálogo e interações de produto.',
    tags: ['React', 'Framer Motion', 'Tailwind'],
    color: '#8f7cff',
  },
  {
    id: 10,
    name: 'ORBIT Agency',
    slug: 'site-agencia-marketing',
    demo: 'https://agencia-mkt-br.vercel.app',
    type: 'Agência',
    segment: 'Marketing',
    desc: 'Agência digital com cases em destaque e serviços organizados em narrativa dinâmica.',
    tags: ['React', 'Framer Motion', 'Tailwind'],
    color: '#8f7cff',
  },
  {
    id: 11,
    name: 'TENGU 天狗',
    slug: 'site-game-tengu',
    demo: 'https://game-tengu.vercel.app',
    type: 'Game',
    segment: 'Concept Site',
    desc: 'Concept site souls-like com brasas em canvas, parallax e direção visual japonesa.',
    tags: ['React', 'Canvas API', 'Framer Motion'],
    color: '#8f7cff',
  },
  {
    id: 12,
    name: 'STAR WARS: ERAS',
    slug: 'site-starwars-eras',
    demo: 'https://starwars-eras.vercel.app',
    type: 'Fan Project',
    segment: 'Scrollytelling',
    desc: 'Viagem por quatro eras da galáxia com ambientação, canvas e scrollytelling.',
    tags: ['React', 'Canvas API', 'Framer Motion'],
    color: '#8f7cff',
  },
]

export const thumbs: Record<string, string> = {
  'roma-massas': '/assets/projects/roma-massas.png',
  'lp-advogado': '/assets/projects/lp-advogado.png',
  'site-tech-startup': '/assets/projects/site-tech-startup.png',
  'lp-dentista': '/assets/projects/lp-dentista.png',
  'lp-tatuador': '/assets/projects/lp-tatuador.png',
  'lp-restaurante': '/assets/projects/lp-restaurante.png',
  'lp-academia': '/assets/projects/lp-academia.png',
  'site-imobiliaria': '/assets/projects/site-imobiliaria.png',
  'lp-saas': '/assets/projects/lp-saas.png',
  'lp-ecommerce-moda': '/assets/projects/lp-ecommerce-moda.png',
  'site-agencia-marketing': '/assets/projects/site-agencia-marketing.png',
  'site-game-tengu': '/assets/projects/site-game-tengu.png',
  'site-starwars-eras': '/assets/projects/site-starwars-eras.png',
}

export const typeFilters = [
  'Todos',
  'Landing Page',
  'Institucional',
  'E-commerce',
  'SaaS',
  'Agência',
  'Game',
  'Fan Project',
]
